version: '3.8'
volumes:
  db-store:
services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: my-php
    volumes:
      - ./code:/var/www/code

  nginx:
    image: nginx:1.19.6-alpine
    container_name: my-nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./code:/var/www/code
    ports:
      - 80:80
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
      LANGUAGE: ja_JP:ja
    depends_on:
      - php

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: my-mysql
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/my.cnf
    ports:
      - 3306:3306
